### ISSUE TITLE
Chapter (4) pkg-config: Markup at the end

### ISSUE THREAD

**Issue by traud** [Flameeyes/autotools-mythbuster#11]
On the Webpage, the introduction page for pkg-config

> https://autotools.io/pkgconfig/

there is red `<xi:include …` after the content and before the footer. All my Web browser have it. DuckDuckGo and Google have it. I looked at the source here in GitHub and do not see why. Perhaps because of the asterisk in file name, the first sub-chapter name?

**Comment by traud** [comment]
Because the issue still exists and this report was not closed: Is more information required to reproduce the issue? Is it reproducible? I am fine if this issue is so minor, it might take time to fix it. However, an acknowledgment that the issue was reproducible would be nice.

**Comment by Flameeyes** [comment]
At this point in time, Autotools Mythbuster is a project I maintain in absolutely spare time. Between the end of year scramble, and the middle of the pandemic, complaining about a few weeks in responses is not really nice.

But yes, I can see that the publishing job has been failing. I'll see to fix it today since I have time.

**Comment by Flameeyes** [comment]
Solved by b4b81f6a3c14734f4e365c5fb10d0017324c4c92

**Comment by traud** [comment]
> not really nice

Upps. I was just asking. I know from my own GitHub that sometimes issues slip through. Or information is missing in Pull Requests which would need additional research, so an ‘understand and confirmed’ is always welcome. Especially because after several weeks I might not even understand my own report anymore and then might not be able to help/clarify.
