### ISSUE TITLE
Explain how compiling

### ISSUE THREAD

**Issue by ghost** [Flameeyes/autotools-mythbuster#5]
Hi.

It would be nice to explain how compiling.

``` shell
$ aptitude search scss
p   python-django-pyscss
p   python-pyscss
p   python-pyscss:i386
p   python-xstatic-bootstrap-scss
p   python3-django-pyscss
p   python3-pyscss
p   python3-pyscss:i386
p   python3-xstatic-bootstrap-scss
$ aptitude search dbtoepub-ns
$ aptitude search dbtoepub
p   dbtoepub
$ 
```
- There are multiple tools in debian main for scss, but which one is correct? I tried `python-pyscss`, but it does not create a symlink for scss.
- `dbtoepub` does not provide `dbtoepub-ns`.

Regards.

**Comment by Flameeyes** [comment]
To be honest, that's well beside the point of this repo, you can see the generated version on autotools.io, that _should_ suffice for most cases, otherwise it's available as ebook already. The availability as a git repo is not for self-compiling, simply put.
