### ISSUE TITLE
No file for Travis CI

### ISSUE THREAD

**Issue by ghost** [Flameeyes/autotools-mythbuster#6]
Hi.

It would be nice to have continuous integration with Travis CI.
Moreover, it will help for https://github.com/Flameeyes/autotools-mythbuster/issues/5.

Regards.

**Comment by Flameeyes** [comment]
Not really worth my time, very simply. As I said on the other issue, this repo is for simple corrections and for general openness, but Travis is overkill particularly as the built version is on autotools.io already.
